# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/generated/*.dart
  errors:
    # https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
linter:
  rules:
    sort_pub_dependencies: false
    use_build_context_synchronously: false
    lines_longer_than_80_chars: false